name: readease
description: "ReadEase - Smart Text Scanner App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Image Picker
  image_picker: ^1.0.7

  # Google ML Kit Text Recognition
  google_mlkit_text_recognition: ^0.13.0

  # Text To Speech
  flutter_tts: ^3.8.5

  # Local Storage
  shared_preferences: ^2.2.2

  # Lottie Animation
  lottie: ^2.7.0

  firebase_core: ^2.25.4
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  google_generative_ai: ^0.4.7
  flutter_dotenv: ^6.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # ADD THIS BLOCK:
  assets:
    - .env
